homeassistant:
  external_url: "https://homeassistant-abcdef-uc.a.run.app"
  internal_url: "https://homeassistant-abcdef-uc.a.run.app"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
  server_host: 0.0.0.0
  server_port: 8123
