homeassistant:
  external_url: "https://homeassistant-free.onrender.com"
  internal_url: "https://homeassistant-free.onrender.com"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1       # localhost IPv4
    - ::1             # localhost IPv6
    - 0.0.0.0/0       # alle proxies (Render)
  trusted_networks:
    - 0.0.0.0/0
  server_host: 0.0.0.0
  server_port: 8123
